### ISSUE TITLE
LGPL compliance is difficult in Rust

### ISSUE THREAD

**Issue by mrtzcspr** [pythops/iwdrs#1]
Hej,
I would be interested in using your crate, but the LGPL license might be an issue because the Rust compilation and linking model makes it effectively GPL code.

Maybe you could consider relicensing it with a more permissive license. For details see e.g. this issue: https://github.com/rpm-software-management/librpm.rs/issues/21

**Comment by pythops** [comment]
Hej,

Personally I like GPL licenses, and I can understand that other people might prefer other licenses. I don't think there is any relation between GPL and rust code. 
I am curious how GPL is stopping you from using this crate ? in other words, what are the problems you are facing using GPL ?

**Comment by mrtzcspr** [comment]
In C/C++ it‘s common to have LGPL licensed code in shared dynamically linked libraries. But in Rust usually everything gets baked in one binary and you would have difficulty to follow up on the license‘s request to:

> „If you link other code with the library, you must provide complete object files to the recipients, so that they can relink them with the library after making changes to the library and recompiling it“

So in the end every crate that uses *iwdrs* would need to be licensed GPL as well. I for example would be potentially interested to use it to interface to iwd in the custom UI of a commercial product. 

I think it‘s a big strength of the Rust crates ecosystem that most of them are licensed in ways that make them accessible for open source enthusiasts and big corporations as well. 

So it‘s of course totally up to you which license you choose, it might just mean that many can‘t use your crate and would have to recreate a similar thing from scratch instead of contributing to your crate.

**Comment by pythops** [comment]
I personally like GPL cause I care about sharing the improvements. I understand that GPL might not be the ideal license for commercial uses but I am fine with that.

> it might just mean that many can‘t use your crate and would have to recreate a similar thing from scratch instead of contributing to your crate.

It's okay for me :)

**Comment by mrtzcspr** [comment]
I was just wondering whether your choice of LGPL (as you chose the full GPL for *impala*) was originally to allow others to use it without forcing the GPL on their full project.

For me a MIT or Apache licensed project would be more encouraging for contributing back, because I would be sure that I could use it for personal as well as work stuff in the future.

But now hard feelings. Thanks anyway for the discussion.

**Comment by mrtzcspr** [comment]
Maybe something to add to this. I think GPL for impala as a complete application is a totally understandable choice. It‘s just the low level library stuff where it would make sense to have only good one that the whole eco system can use with being restricted license wise.

**Comment by pythops** [comment]
I like the GPL because it encourages for contributing back, and for that reason almost all my code is GPL licensed. I honestly don't like other permissive licenses cause many commercial uses don't contribute back whether by code or by money, so for me personally, it kind of unfair for the author. 

If people want to use `iwdrs` then yes, they need to comply with the GPL constraints, otherwise they can create their own with the license of their choice. 

I think there is no good or bad license here, it just depends on how do you want your code to be used :)

**Comment by pythops** [comment]
I am not planning to change the license, so I guess we can close this ticket.
Thanks for the interesting conversation :)
